### ISSUE TITLE
Creating child note from parent

### ISSUE THREAD

**Issue by dboshardy** [dendronhq/dendron-template#34]
I'm really enjoying Dendron so far, but as I start getting deeper into hierarchies, it gets cumbersome to write out the entire path as a backlink and then use the `Go To` shortcut to create it.  Is there a command to pre-populate the descendent branch or a better way of doing this workflow so I can just add the child note name and then create it?

**Comment by kevinslin** [comment]
when you use [lookup](https://dendron.so/notes/a7c3a810-28c8-4b47-96a6-8156b1524af3.html) in any note, it automatically pre-populates with the current path. you can just add the child you want to create at the end

**Comment by dboshardy** [comment]
I'm not sure I understand.  Let's say I'm in `projects.my-proj.view` and want to create a new child note such that it creates `projects.my-proj.view.home`. I want to be able to create it by typing just `home` and, with the context being that I'm in this `projects.my-proj.view` note, it will create it as a child of that note.  If I Lookup `home` it will create a `home.md` file, not the child file with the ancestry.

**Comment by kevinslin** [comment]
If you bring up `Lookup`, you should see the current path highlighted (eg. `
projects.my-proj.view`)
you will need to first hit the right arrow key to move the cursor to the
end of the selection and then type home. This will create `projects.my-proj.
home`.
the reason for the arrow key is because vscode doesn't allow us to control
the cursor of the lookup component at this time

**Comment by dboshardy** [comment]
Interesting. I must have to mess with my shortcuts.  As it is now, my Lookup note shortcut is CMD + ^ + S which when I use it, creates a new scratch note.  To do a lookup, i have to  power bar > "dendron: lookup" and select it that way.  I must have borked my shortcuts.
